# Generated by Django 3.2 on 2024-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_уникальный отзыв'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='уникальный отзыв',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title_id', 'author_id'), name='уникальный отзыв'),
        ),
    ]
