# Generated by Django 3.2 on 2024-05-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20240512_2020'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='уникальный отзыв',
        ),
    ]
